### ISSUE TITLE
Img card

### ISSUE THREAD

**Issue by Nidev-lab** [rafaortega191/rollingRestaurant-frontend#85]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que todas las cards tengan la imagen de sus respectivos productos.

## Resultado actual

• Una cards no carga la imagen del producto y muestra un error por consola.

## Captura

![image](https://github.com/rafaortega191/rollingRestaurant-frontend/assets/53904695/0b826a4c-4412-4a6a-b1aa-9eb9db7b29d3)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas chicos! Como están? Estuve revisando el proyecto y la verdad que esta muy bien logrado, a excepción de algunas cosas muy minúsculas que encontré, pero fuera de eso esta todo ok, se las dejare cargadas.
Para poder terminar con la devolución del proyecto necesitaría un user admin, tendrían algún usuario admin que me pasen?

**Comment by rafaortega191** [comment]
Buenas tardes Nico, soy Rafa el scrum master del grupo, aquí te paso un
usuario con permiso de administrador que podrás ocupar.
correo electrónico: ***@***.***
contraseña: Aa246810

en cuanto al tema de los issues, cuando deberíamos empezar a arreglarlos,
saludos.

**Comment by Nidev-lab** [comment]
Hola Rafa, pueden empezar cuando quieran, a medida que las issues se cargan las pueden ir resolviendo sin problemas.

**Comment by rafaortega191** [comment]
Hola Nico el error de las cards ya se encuentra solucionado, era debido a que la imagen esta sujeta a un link el cual ya no funcionaba.
