### ISSUE TITLE
Carrito pedidos

### ISSUE THREAD

**Issue by Nidev-lab** [rafaortega191/rollingRestaurant-frontend#88]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Agregue uno pedidos al carrito.

## Resultado esperado

• Encontrar un max de productos a comprar.

## Resultado actual

• Puedo colocar numeros infinitos a la hora de ordenar un producto.

## Captura

![image](https://github.com/rafaortega191/rollingRestaurant-frontend/assets/53904695/f4aa6792-48d4-434d-8232-25e91258c8e7)
![image](https://github.com/rafaortega191/rollingRestaurant-frontend/assets/53904695/b4fc653e-2cc7-4341-a1f4-4868e53bcd20)
![image](https://github.com/rafaortega191/rollingRestaurant-frontend/assets/53904695/bb5d57b0-219e-4271-9dc6-48b9a14a4c5d)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by rafaortega191** [comment]
Hola Nico, se soluciono ese error, ahora cada producto tiene un contador que se puede subir o bajar hasta 25 unidades y empieza siempre en 1.
