### ISSUE TITLE
Registro

### ISSUE THREAD

**Issue by Nidev-lab** [rafaortega191/rollingRestaurant-frontend#90]
## Proceso

1. Ingrese a la pagina.
2. Quise crear un nuevo usuario.

## Resultado esperado

• Que no me tome como usuario valido si solo coloco espacios sin ningún tipo de caracteres.

## Resultado actual

• Se toman como validos los espacios sin ningun tipo de caracteres en el nombre de usuario.

## Captura

![image](https://github.com/rafaortega191/rollingRestaurant-frontend/assets/53904695/e75b1470-4226-4000-99a9-4faa013eff80)
![image](https://github.com/rafaortega191/rollingRestaurant-frontend/assets/53904695/0a7e217f-25de-4070-bb43-5630cf4e307d)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by EugeniaCaceres** [comment]
Agregué el cambio corregido en el pr #91
