### ISSUE TITLE
Nombre de usuario

### ISSUE THREAD

**Issue by Nidev-lab** [rafaortega191/rollingRestaurant-frontend#95]
## Proceso

1. Ingrese a la pagina.
2. Quise crear un nuevo usuario.
 
## Resultado esperado

• Encontrar un min de caracteres a colocar. 
• Que no se puedan colocar numeros ni signos.

## Resultado actual

• Al colocar un solo carácter me lo toma como nombre de usuario valido.
• Se permiten colocar numeros y signos.

## Captura

![image](https://github.com/rafaortega191/rollingRestaurant-frontend/assets/53904695/204fdd59-da01-42b0-b676-5e04435e5e9d)
![image](https://github.com/rafaortega191/rollingRestaurant-frontend/assets/53904695/60c7f219-e49e-4018-b2fc-633205c0a541)

PD: min recomendado 4 caracteres

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by rafaortega191** [comment]
Hola Nico, ya se corrigió el error en la pagina de registro. Saludos.
